### What a tensor represents

In [2]:
import tensorflow as tf
import numpy as np

2023-05-29 17:19:28.449322: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-29 17:19:29.475032: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [5]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
print(np.array(3))

tf.Tensor(4, shape=(), dtype=int32)
3


In [6]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
print(np.array([1.0, 2.0, 3.0]))

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
[1. 2. 3.]


In [10]:
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)
print(np.array([[1,2,3],
               [4,5,6],
               [7,8,9]]))

tf.Tensor(
[[[1. 2.]
  [3. 4.]
  [5. 6.]]

 [[1. 2.]
  [3. 4.]
  [5. 6.]]], shape=(2, 3, 2), dtype=float16)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(np.array([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],]))

<class 'tensorflow.python.framework.ops.EagerTensor'>
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [13]:
np.array(rank_1_tensor)

array([2., 3., 4.], dtype=float32)

In [14]:
rank_2_tensor.numpy()

array([[[1., 2.],
        [3., 4.],
        [5., 6.]],

       [[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float16)

In [15]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [16]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [22]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [32]:
tf.math.reduce_mean(tf.reshape(c,[-1]))

tensorflow.python.framework.ops.EagerTensor

In [3]:
np.array([[[0],
          [0]],[[0],
          [0]]]).shape

(2, 2, 1)

In [4]:
np.array([[[1, 2, 3], 
          [4, 5, 6], 
          [4, 5, 6]],
                    [[1, 2, 3], 
                    [4, 5, 6], 
                    [4, 5, 6]]]).ndim

3