In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

### Data Genration

In [3]:
observations = 1000

# generated_inputs = np.random.uniform(low=-10, high=10, size=(observations, 2))
xs = np.random.uniform(low=-10, high=10, size=(observations, 1))
zs = np.random.uniform(-10, 10, (observations, 1))
generated_inputs = np.column_stack((xs, zs))

noise = np.random.uniform(-1,1, (observations, 1))

generated_targets = 2*xs - 3*zs + noise

np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

### Solving with TensorFlow

In [4]:
training_data = np.load('TF_intro.npz' )
training_data['inputs'].shape
training_data['targets'].shape

(1000, 1)

#### build the model
* Data: we have generated some fake data.
* Model: our model we want to build is linear.
* Objective function (loss function): 
    * we want it L2_norm
    * L2_norm is scaled SSE
    * scalled SSE is the same as MSE (mean squared error)
* Optimization algorithm: we want gradient descent. in TF we can stochastic gradient descent SGD

##### guidelines for determining the batch size:
* For small datasets, use a small batch size, such as 16 or 32.
* For large datasets, use a larger batch size, such as 128 or 256.
* If the model is overfitting, try using a smaller batch size.
* If the model is not converging, try using a larger batch size.
* Experiment with different batch sizes to find the best performance on a held-out validation set.

In [10]:
# in numpy code: output = np.dot(inputs, weight) + noise
# tf.keras.layers.Dense() takes the input provided to the model and calculates the dot product of the inputs and the weights and adds the bias
input_size = 2
output_size = 1

model = tf.keras.Sequential([
                            tf.keras.layers.Dense(
                                output_size,
                                kernel_initializer = tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                bias_initializer = tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                )
                            ])
# custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
custom_optimizer = tf.keras.optimizers.Adam()
# model.compile(optimizer=custom_optimizer, loss='mean_squared_error')
model.compile(optimizer=custom_optimizer, loss='huber_loss')
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2, batch_size=10)
#

Epoch 1/100
100/100 - 0s - loss: 15.7387 - 322ms/epoch - 3ms/step
Epoch 2/100
100/100 - 0s - loss: 15.1773 - 117ms/epoch - 1ms/step
Epoch 3/100
100/100 - 0s - loss: 14.6131 - 134ms/epoch - 1ms/step
Epoch 4/100
100/100 - 0s - loss: 14.0518 - 153ms/epoch - 2ms/step
Epoch 5/100
100/100 - 0s - loss: 13.4917 - 150ms/epoch - 2ms/step
Epoch 6/100
100/100 - 0s - loss: 12.9333 - 148ms/epoch - 1ms/step
Epoch 7/100
100/100 - 0s - loss: 12.3740 - 152ms/epoch - 2ms/step
Epoch 8/100
100/100 - 0s - loss: 11.8177 - 147ms/epoch - 1ms/step
Epoch 9/100
100/100 - 0s - loss: 11.2630 - 146ms/epoch - 1ms/step
Epoch 10/100
100/100 - 0s - loss: 10.7071 - 150ms/epoch - 1ms/step
Epoch 11/100
100/100 - 0s - loss: 10.1544 - 149ms/epoch - 1ms/step
Epoch 12/100
100/100 - 0s - loss: 9.6006 - 146ms/epoch - 1ms/step
Epoch 13/100
100/100 - 0s - loss: 9.0493 - 147ms/epoch - 1ms/step
Epoch 14/100
100/100 - 0s - loss: 8.4988 - 152ms/epoch - 2ms/step
Epoch 15/100
100/100 - 0s - loss: 7.9477 - 149ms/epoch - 1ms/step
Epoch 16

#### Extract the weights and bias
our actual equation is 2x - 3z + 5 + noise

In [8]:
model.layers[0].get_weights()

[array([[ 1.9968292],
        [-2.997725 ]], dtype=float32),
 array([-0.00948432], dtype=float32)]

In [100]:
model.layers[0].get_weights()[0]

array([[ 1.9938639],
       [-2.9972506]], dtype=float32)

In [101]:
model.layers[0].get_weights()[1]

array([-0.00051713], dtype=float32)

#### Extract outputs (make predictions)

In [102]:
model.predict_on_batch(training_data['inputs']).round(1)

array([[-11.8],
       [  7.6],
       [  0.1],
       [ 24.1],
       [ 14.1],
       [  1.1],
       [ 12.2],
       [-10.7],
       [ 21.3],
       [ 13.3],
       [-19.8],
       [ 30.5],
       [  5.8],
       [-10. ],
       [ -9. ],
       [ -3. ],
       [ -8.9],
       [  7.5],
       [  2.5],
       [-26.9],
       [ 30. ],
       [ 19.9],
       [ -6. ],
       [ 13.6],
       [  3.5],
       [ 12.2],
       [ 16.9],
       [  9.1],
       [-14.3],
       [ -2.4],
       [ 41.7],
       [  4.8],
       [ 45.8],
       [-15.2],
       [  1.6],
       [ 30.9],
       [ 14.5],
       [-17.8],
       [  5.2],
       [ -3.3],
       [ 18.1],
       [-20.9],
       [ -5.3],
       [ 29.7],
       [ 32.8],
       [  3.2],
       [-22.1],
       [-10.4],
       [ 31.3],
       [ 30.8],
       [-15.5],
       [-19.6],
       [  3.6],
       [ -8.3],
       [-44.3],
       [ -8.4],
       [  6.9],
       [ -2.8],
       [-13.6],
       [ 19.6],
       [ -3.1],
       [  9.9],
       [

In [103]:
training_data['targets'].round(1)

array([[-10.9],
       [  6.8],
       [ -0.2],
       [ 24.4],
       [ 13.2],
       [  1.7],
       [ 12.3],
       [-11.3],
       [ 21.5],
       [ 12.7],
       [-20.8],
       [ 31.2],
       [  4.9],
       [-10.6],
       [ -8.2],
       [ -2.4],
       [ -8. ],
       [  8.2],
       [  2.3],
       [-27.9],
       [ 30.6],
       [ 20.1],
       [ -5.6],
       [ 13. ],
       [  4.3],
       [ 11.4],
       [ 16.3],
       [  8.5],
       [-14.5],
       [ -2.2],
       [ 42.5],
       [  4.1],
       [ 45.6],
       [-14.8],
       [  0.7],
       [ 31.7],
       [ 14.7],
       [-17.9],
       [  4.8],
       [ -3.9],
       [ 18.8],
       [-20. ],
       [ -6. ],
       [ 30.1],
       [ 33.1],
       [  4.1],
       [-21.7],
       [ -9.9],
       [ 30.7],
       [ 30.6],
       [-14.6],
       [-18.8],
       [  3.8],
       [ -7.6],
       [-43.9],
       [ -8.7],
       [  6.4],
       [ -2.5],
       [-13.4],
       [ 19.9],
       [ -2.4],
       [ 10.7],
       [

In [104]:
#plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))